function build_SparseGPs_array_tau_neural(hyperparam)

    global sparseGPs
    
    for i=1:length(sparseGPs)
        
        sparseGPs(i).sparseGP_x = build_sparseGP_tau_neural(sparseGPs(i).data.x, ...
                                                          sparseGPs(i).data.y, ...
                                                          sparseGPs(i).data.tau, ...
                                                          sparseGPs(i) ...
                                                          .data.dx_dt, ...
                                                          hyperparam);
        
        sparseGPs(i).sparseGP_y = build_sparseGP_tau_neural(sparseGPs(i).data.x, ...
                                                          sparseGPs(i).data.y, ...
                                                          sparseGPs(i).data.tau, ...
                                                          sparseGPs(i) ...
                                                          .data.dy_dt, ...
                                                          hyperparam);        
    end

end
