function initialize_SparseGPs_array_tau(hyperparam)

% draws n random trajectories and form GP for each
    
    global sparseGPs trajs
    sparseGPs = {};
    samples = randsample(1:trajs.n_traj, trajs.n_clus);
    
    for i=1:trajs.n_clus
       
        sparseGPs(i).sparseGP_x = ...
            build_sparseGP_tau(trajs.data(samples(i)).x, ...
                               trajs.data(samples(i)).y, ...
                               trajs.data(samples(i)).tau, ...
                               trajs.data(samples(i)).dx_dt, ...
                               hyperparam);
        
        sparseGPs(i).sparseGP_y = ...
            build_sparseGP_tau(trajs.data(samples(i)).x, ...
                               trajs.data(samples(i)).y, ...
                               trajs.data(samples(i)).tau, ...
                               trajs.data(samples(i)).dy_dt, ...
                               hyperparam);
        
    end

end
